apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-users
  labels:
    app: api-users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-users
  template:
    metadata:
      labels:
        app: api-users
    spec:
      containers:
      - name: udagram-api-users
        image: aguillenv93/udagram-api-users:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_USERNAME
          value: postgres
        - name: POSTGRES_PASSWORD
          value: Argv1993
        - name: POSTGRES_HOST
          value: cdr.clpezd1yx0o8.eu-west-3.rds.amazonaws.com
        - name: POSTGRES_DB
          value: postgres
        - name: AWS_BUCKET
          value: udagram-947997470987-dev
        - name: AWS_REGION
          value: eu-west-3
        - name: AWS_PROFILE
          value: default
        - name: JWT_SECRET
          value: my-secret
